name: fldamiens
root: ./
pre_window: nvm use 16

windows:
  - front:
      root: front
      layout: tiled
      panes:
        - yarn run dev
        - ./node_modules/.bin/tsc --watch
  - back:
      layout: tiled
      panes:
        - symfony server:start