name: PHP Workflow

on:
  push:

env:
  DATABASE_NAME: fldamiens_test
  DATABASE_USER: postgres
  DATABASE_PASSWORD: postgres

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11-buster
        env:
          POSTGRES_USER: ${{ env.DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ env.DATABASE_PASSWORD }}
          POSTGRES_DB: ${{ env.DATABASE_NAME }}
          TZ: "Europe/Paris"
        ports:
          - 5432/tcp
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: set timezone
        run: sudo timedatectl set-timezone Europe/Paris

      - name: checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: pgsql
          coverage: none
          ini-values: date.timezone=Europe/Paris, opcache.enable = 1, opcache.enable_cli = 1, opcache.memory_consumption = 128, opcache.max_accelerated_files = 4000, opcache.revalidate_freq = 60, opcache.save_comments = 1, opcache.fast_shutdown = 1, output_buffering = 81920
          tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run database migrations
        run: |
          php bin/console doctrine:migrations:migrate --no-interaction --env=test
        env:
          DATABASE_URL: pgsql://${{ env.DATABASE_USER }}:${{ env.DATABASE_PASSWORD }}@127.0.0.1:${{ job.services.postgres.ports[5432] }}/fldamiens?charset=UTF-8

      - name: Run test phpunit / behat
        run: |
          ./vendor/bin/phpunit
        env:
          DATABASE_URL: pgsql://${{ env.DATABASE_USER }}:${{ env.DATABASE_PASSWORD }}@127.0.0.1:${{ job.services.postgres.ports[5432] }}/fldamiens?charset=UTF-8

      - name: cat logs on failure
        if: failure()
        run: cat ./var/log/test.log
